// Generated by LiveScript 1.4.0
(function(){
  var livescript, translate, out$ = typeof exports != 'undefined' && exports || this;
  livescript = require('livescript');
  out$.translate = translate = function(load){
    var output;
    output = livescript.compile(load.source, {
      filename: load.address,
      map: true,
      bare: true
    });
    return load.source = output.code;
  };
}).call(this);
